Models/ProductEntity.cs
namespace Mediafy.Models
{
    public class ProductEntity
    {
        public ProductModel Product { get; set; }
        public int ViewCount { get; set; }
    }
}

Models/ProductModel.cs
using Newtonsoft.Json;

namespace Mediafy.Models
{
    public class ProductModel
    {
        [JsonProperty("name")]
        public string Name { get; set; }
        
        [JsonProperty("fromPrice")]
        public string FromPrice { get; set; }
        
        [JsonProperty("image")]
        public string Image { get; set; }
        
        [JsonProperty("description")]
        public string Description { get; set; }
        
        public string Slug { get; set; }
    }
}

Models/ProductViewModel.cs
using System.Collections.Generic;

namespace Mediafy.Models
{
    public class ProductViewModel
    {
        public ProductViewModel(List<ProductModel> products)
        {
            Products = products;
        }

        public List<ProductModel> Products { get; set; }
    }
}

Controllers/ProductController.cs
using Mediafy.Models;
using Mediafy.Queries;
using Microsoft.AspNetCore.Mvc;

namespace Mediafy.Controllers
{
    public class ProductController : Controller
    {
        private readonly IGetProductQuery _getProductQuery;

        public ProductController(IGetProductQuery getProductQuery)
        {
            _getProductQuery = getProductQuery;
        }

        public ActionResult<ProductViewModel> Index()
        {
            var products = _getProductQuery.GetProducts();
            return View(new ProductViewModel(products));
        }
        
        [HttpGet("/{productName}")]
        public ActionResult<ProductModel> ProductCard(string productName)
        {
            var product = _getProductQuery.GetProduct(productName);
            return View(product);
        }
    }
}

Views/Product/Index.cshtml
@model Mediafy.Models.ProductViewModel

@{
    ViewBag.Title = "Populära tidningar";
    Layout = "_Layout";
}

<h2 class="product-title">Populära tidningar</h2>

<div class="productcard-container">
    @foreach (var product in Model.Products)
    {
        <div class="productcard js-productcard" data-url="@Url.Action("ProductCard", "Product", new {productName = product.Slug})">
            <div class="productcard__img-container">
                <img class="productcard__img-container" src="@product.Image" width="40"/>
            </div>
            <div class="productcard__name">@product.Name</div>
            <div class="productcard__price">@product.FromPrice</div>
            <div class="productcard__read-more">Läs mer</div>
        </div>
    }
</div>

Views/Product/ProductCard.cshtml
@model Mediafy.Models.ProductModel

@{
    ViewBag.Title = Model.Name;
    Layout = "_Layout";
}

<h2 class="product-title">@Model.Name</h2>

<div class="product-content">
    <div class="product-content__img-container">
        <img src="@Model.Image" width="40"/>
    </div>
    <div class="product-content__text-container">
        <div class="product-content__text-container__description">@Model.Description</div>
        <div class="product-content__text-container__price">@Model.FromPrice <span class="cta-button">Lägg till i varukorg</span></div>
        
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mediafy</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Product" asp-action="Index" class="navbar-brand">Mediafy</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Product" asp-action="Index">Produkter</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

   <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Mediafy</p>
        </footer>
    </div>

@RenderSection("Scripts", required: false)
</body>
</html>